### ISSUE TITLE
Runtime metric to count Tasks in the DONE state

### ISSUE THREAD

**Issue by abliznyuk** [ametiste-oss/ametiste-routine-framework#15]
**Story**

As an Operational User, I want to have metrics to estimate number of tasks that was done during runtime session, so that I can see the operational progress.

**Implementation**
- `CoreStats` subsystem counts `TaskDone` domain events during runtime
- `core.info.done-tasks-count` metric gauge to show aggregated results by period
- `/core/stat` location to show realtime statistics

Graphite graph variant
![render-53](https://cloud.githubusercontent.com/assets/276144/14524781/acf0608a-0242-11e6-851e-8d98799cf03c.png)

**Limitations**
- Only single (and current) session metrics will be shown, at the moment there is no accurate way to store these values, for example when application is exit unexpected. 

**Technical Details**
- pub-sub jms domain enabled, before this feature `Queue` was good enough to store domain events
- `TaskEvents` value object involved to represent a set of domain events, its planed to be used as base point for events subsystem refactoring at the time of `1.2.x`.

**Comment by detsam** [comment]
Implemented at https://github.com/ametiste-oss/ametiste-routine-framework/commit/75f9ebfc42c9ea1ae4a7d50cc7feefc8d6830943
